---
- hosts: Backend_movie_analyst
  become_user: root
  become: yes
  become_method: sudo
  vars:
    NODE_ENV: 'production'
    DB_USER: 'applicationuser'
    DB_NAME: 'movie_db'
    PORT: 3000

  tasks:
    - name: Clone movie-analyst-api from GitHub
      ansible.builtin.git:
        repo: https://github.com/MateoRincon04/movie-analyst-api.git
        dest: ~/movie-analyst-api
        force: yes
        single_branch: yes
        version: master

    - name: Run common role
      include_role:
        name: common
      vars:
        ansible_app_dir: '~/movie-analyst-api'

    - name: Install mysql-client
      package:
        name: mysql-client
        state: present

    - name: Run mysql
      ansible.builtin.shell:
        cmd: mysql -h {{DB_HOST}} -P 3306 -u {{DB_USER}} --password={{DB_PASS}} < ~/movie-analyst-api/data_model/table_creation_and_inserts.sql

    - name: Run application using pm2
      command: 'NODE_ENV={{NODE_ENV}} DB_USER={{DB_USER}} DB_NAME={{DB_NAME}}" PORT=3000 DB_HOST={{DB_HOST}} pm2 start server.js --update-env'
