---
- hosts: Backend_movie_analyst
  become_user: root
  become: yes
  become_method: sudo
  vars:
    NODE_ENV: 'production'
    DB_USER: 'applicationuser'
    DB_NAME: 'movie_db'
    PORT: 3000

  tasks:
    - name: Clone movie-analyst-api from GitHub
      ansible.builtin.git:
        repo: https://github.com/MateoRincon04/movie-analyst-api.git
        dest: ~/movie-analyst-api
        force: yes
        single_branch: yes
        version: master

    - name: Run common role
      include_role:
        name: common
      vars:
        ansible_app_dir: '~/movie-analyst-api'

    - name: Install mysql-client
      package:
        name: mysql-client
        state: present

    - name: install python-setuptools
      package:
        name: python3-setuptools
        state: present

    - name: Install pip
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Update pip3
      ansible.builtin.shell:
        cmd: pip3 install --upgrade pip

    - name: Install pip3 required libraries
      pip:
        name: pymysql
        state: present

    - name: Get community.mysql collection from ansible-galaxy
      ansible.builtin.shell:
        cmd: ansible-galaxy collection install community.mysql

    - name: Import database configuration into RDS
      community.mysql.mysql_db:
        state: import
        name: "{{DB_NAME}}"
        login_user: "{{DB_USER}}"
        login_password: "{{DB_PASS}}"
        login_host: "{{DB_HOST}}"
        target: ./data_model/table_creation_and_inserts.sql

    - name: Run application using pm2
      command: 'pm2 start server.js'
