---
- hosts: Frontend_movie_analyst
  remote_user: root
  become: yes
  become_method: sudo
  vars:
    NODE_ENV: 'production'

  tasks:
    - name: Clone movie-analyst-ui from GitHub
      ansible.builtin.git:
        repo: https://github.com/MateoRincon04/movie-analyst-ui.git
        dest: ~/movie-analyst-ui
        force: yes
        single_branch: yes
        version: master

    - name: Run common role
      include_role:
        name: common
      vars:
        ansible_app_dir: '~/movie-analyst-ui'

    - name: Run application using pm2
      ansible.builtin.shell:
        cmd: BACK_HOST={{BACK_HOST}} NODE_ENV={{NODE_ENV}} pm2 start server.js --update-env
